SELECT * FROM DEPARTAMENTO;
SELECT COD_DEP AS "CÓDIGO DEPARTAMENTO", NOME_DEP FROM DEPARTAMENTO;
SELECT DISTINCT COD_DEP FROM EMPREGADO;
SELECT * FROM EMPREGADO ORDER BY NOME, SOBRENOME DESC;
SELECT NOME,SALARIO FROM EMPREGADO WHERE COD_DEP = 100;
SELECT NOME,SALARIO FROM EMPREGADO WHERE COD_DEP IS NULL;
SELECT NOME,SALARIO FROM EMPREGADO WHERE SALARIO <= 10500
;
SELECT * 
FROM EMPREGADO 
WHERE COD_DEP = 100 
AND SALARIO >= 8000 
AND COD_GERENTE = 108
;
SELECT COD_EMP, NOME, COD_GERENTE
FROM EMPREGADO 
WHERE (COD_GERENTE = 108
OR COD_GERENTE = 103)
AND NOME = 'Bruce'
;
SELECT COD_EMP, NOME, COD_GERENTE
FROM EMPREGADO 
WHERE (COD_GERENTE = 108
OR COD_GERENTE = 103)
;
SELECT COD_EMP, NOME, COD_GERENTE
FROM EMPREGADO 
WHERE COD_GERENTE IN (108, 103)
;
SELECT * FROM EMPREGADO WHERE NOME LIKE '%tt%';
SELECT * FROM EMPREGADO WHERE EMAIL LIKE '%BRAU';
SELECT * FROM EMPREGADO WHERE SOBRENOME LIKE '__ %';
SELECT NOME
FROM EMPREGADO
WHERE NOME LIKE '%r'
;
SELECT NOME, SALARIO, COD_DEP
FROM EMPREGADO
WHERE (SALARIO >= 8000 AND COD_DEP = 50)
OR NOME = 'Oliver'
;
SELECT NOME, LOWER(NOME), UPPER(NOME)
FROM EMPREGADO
WHERE SALARIO > 7100
;
SELECT NOME || ' ' || SOBRENOME AS "NOME COMPLETO"
FROM EMPREGADO
;
SELECT NOME, SUBSTR(NOME, 1, 3), SUBSTR(NOME, 4)
FROM EMPREGADO
;
SELECT *
FROM EMPREGADO
WHERE LENGTH(NOME) = 3
;
SELECT NOME,
DATA_CONTRATACAO, 
DATA_CONTRATACAO + 60, 
DATA_CONTRATACAO - 60,
SYSDATE - DATA_CONTRATACAO
FROM EMPREGADO
;
SELECT SYSDATE, SYSDATE + 60, SYSDATE - 60
FROM DUAL
;
SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'),
TO_CHAR(SYSDATE + 1/24, 'DD/MM/YYYY HH24:MI:SS'),
TO_CHAR(SYSDATE + 1/24/60, 'DD/MM/YYYY HH24:MI:SS'),
TO_CHAR(SYSDATE + 1/24/60/60, 'DD/MM/YYYY HH24:MI:SS')
FROM DUAL
;
SELECT TRUNC(SYSDATE, 'MM'), TRUNC(SYSDATE, 'YYYY')
FROM DUAL
;
SELECT SYSDATE, 
(SYSDATE + 2), 
LAST_DAY(SYSDATE), 
ADD_MONTHS(LAST_DAY(SYSDATE), 1)
FROM DUAL
;
SELECT SYSDATE, NEXT_DAY(SYSDATE, 7)
FROM DUAL
;
SELECT TO_CHAR(TO_DATE('29/03/2017 11:56:08', 'DD/MM/YYYY HH24:MI:SS'), 'DD/MM/YYYY HH24:MI:SS')
FROM DUAL
;
SELECT NOME, 
PCT_COMISSAO, 
TO_CHAR(12345678 + PCT_COMISSAO, '99,999,999,999,990.00')
FROM EMPREGADO
WHERE PCT_COMISSAO IS NOT NULL
;
SELECT VALOR,
TO_CHAR(VALOR, '99,999,999,999,990.00'),
REPLACE(REPLACE(REPLACE(TO_CHAR(VALOR, '99,999,999,999,990.00'), '.', 'b'), ',', '.'), 'b', ','),
TRANSLATE(TO_CHAR(VALOR, '99,999,999,999,990.00'), ',.', '.,')
FROM (
  SELECT 12345678.99 VALOR
  FROM DUAL
)
;
SELECT NOME
FROM (
  SELECT *
  FROM EMPREGADO
)
;
SELECT TO_CHAR(TO_DATE('20130905','YYYYMMDD'),'DD-MON-YYYY') FROM DUAL
;
SELECT TO_NUMBER('23,11')
FROM DUAL
;
SELECT NOME, PCT_COMISSAO, COALESCE(PCT_COMISSAO, 0)
FROM EMPREGADO
;
SELECT COALESCE(DATA_REF, SYSDATE) AS DATA_REF
FROM (
  SELECT SYSDATE + 10 AS DATA_REF FROM DUAL
  UNION ALL
  SELECT NULL FROM DUAL
)
;
SELECT DISTINCT COALESCE(COD_DEP, 0) FROM EMPREGADO 
;
SELECT NOME, COD_GERENTE, SALARIO
FROM EMPREGADO
WHERE SALARIO > 15000
UNION ALL
SELECT NOME_DEP, COD_GERENTE, COD_LOCAL
FROM DEPARTAMENTO
WHERE COD_GERENTE IS NOT NULL
;
SELECT SALARIO, PCT_COMISSAO, SALARIO + COALESCE(PCT_COMISSAO, 0)
FROM EMPREGADO 
WHERE COD_DEP=90
;
SELECT NOME,
       CASE 
         WHEN SALARIO < 2000 THEN 'Baixo'
         WHEN SALARIO > 5000 THEN 'Alto'
         ELSE 'Médio'
       END AS SALARIO
FROM EMPREGADO
;
SELECT NOME,
       CASE PCT_COMISSAO
         WHEN 0.3 THEN 30
         WHEN 0.4 THEN 40
         ELSE 0
       END AS SALARIO
FROM EMPREGADO
;
SELECT UPPER(NOME), SOBRENOME
FROM EMPREGADO
WHERE UPPER(NOME) LIKE '%TT%'
;
SELECT *
FROM (
  SELECT UPPER(NOME) AS NOME, SOBRENOME
  FROM EMPREGADO
)
WHERE NOME LIKE '%TT%'
;
SELECT ROUND(3.465, 2), ROUND(3.464, 2)
FROM DUAL
;
SELECT TRUNC(3.46999999999999999999, 2), TRUNC(3.464, 2)
FROM DUAL
;
SELECT TRUNC(3.46999999999999999999, 0), TRUNC(3.464)
FROM DUAL
;
SELECT TO_CHAR(SYSDATE + 60/24/60, 'DD/MM/YYYY HH24:MI:SS')
FROM DUAL
;
SELECT TO_CHAR(0.99, '999,999,999,000.00')
FROM DUAL
;
SELECT AVG(SALARIO) AS "MEDIA DOS SALARIOS", 
       COUNT(COD_EMP) AS QTD,
       MIN(SALARIO),
       MAX(SALARIO),
       SUM(SALARIO)
FROM EMPREGADO
;
SELECT COUNT(*),
       COUNT(1),
       COUNT(COD_EMP),
       COUNT(SALARIO),
       COUNT(COD_DEP),
       COUNT(PCT_COMISSAO)
FROM EMPREGADO
;
SELECT COD_DEP, COD_GERENTE,
       ROUND(AVG(SALARIO), 2) AS "MEDIA DOS SALARIOS", 
       COUNT(COD_EMP) AS QTD,
       MIN(SALARIO),
       MAX(SALARIO),
       SUM(SALARIO)
FROM EMPREGADO
GROUP BY COD_DEP, COD_GERENTE
ORDER BY MIN(SALARIO)
;
SELECT COD_DEP, COUNT(*) AS TOTAL
FROM EMPREGADO
GROUP BY COD_DEP
HAVING COUNT(*) > 20
;
SELECT *
FROM REGIAO
;
SELECT NOME_PAIS
FROM PAIS
;
SELECT CIDADE
FROM LOCAL
;
SELECT NOME, PCT_COMISSAO AS "Comissao"
FROM EMPREGADO
;
SELECT NOME_SERVICO, SALARIO_MAX - SALARIO_MIN AS "Dif"
FROM SERVICO
ORDER BY "Dif" DESC
;
SELECT DISTINCT COD_LOCAL
FROM DEPARTAMENTO
;
SELECT DISTINCT COD_GERENTE
FROM EMPREGADO
ORDER BY COD_GERENTE DESC
;
SELECT DISTINCT COD_GERENTE
FROM DEPARTAMENTO
ORDER BY COD_GERENTE DESC
;
SELECT COD_DEP, NOME, SOBRENOME
FROM EMPREGADO
ORDER BY 1 DESC, 2, 3
;
SELECT COD_EMP, DATA_INICIO
FROM HISTORIA_EMPREGADO
WHERE COD_SERVICO IN ('IT_PROG', 'SA_MAN')
;
SELECT COD_EMP, DATA_INICIO
FROM HISTORIA_EMPREGADO
WHERE COD_SERVICO = 'IT_PROG'
OR COD_SERVICO = 'SA_MAN'
;
SELECT NOME_SERVICO
FROM SERVICO
WHERE SALARIO_MIN < 4500
OR SALARIO_MAX > 12000
;
SELECT COD_LOCAL
FROM LOCAL
WHERE CEP IS NULL
;
SELECT CIDADE
FROM LOCAL
WHERE CIDADE LIKE 'S%'
;
SELECT CIDADE
FROM LOCAL
WHERE CIDADE >= 'S'
;
SELECT COD_EMP, DATA_INICIO
FROM HISTORIA_EMPREGADO
WHERE COD_SERVICO IN ('SA_MAN', 'IT_PROG')
;
SELECT NOME_SERVICO, SALARIO_MIN, SALARIO_MAX
--SELECT *
FROM SERVICO
WHERE SALARIO_MIN < 4500 
OR SALARIO_MAX > 12000
;
SELECT COD_LOCAL
FROM LOCAL
WHERE CEP IS NULL
;
SELECT TO_CHAR(TO_DATE('20110123 13:24:14', 'YYYYMMDD HH24:MI:SS'), 'DD/MM/YYYY HH24-MI-SS')
FROM DUAL
;
SELECT LAST_DAY(SYSDATE)
FROM DUAL
;
SELECT TO_CHAR(NEXT_DAY(SYSDATE, 7), 'DD/MM/YYYY')
FROM DUAL
;
SELECT TO_CHAR(SYSDATE+3, 'DD/MM/YYYY')
FROM DUAL
;
SELECT TO_DATE('15/09/2015', 'DD/MM/YYYY') - TO_DATE('01/02/2015', 'DD/MM/YYYY')
FROM DUAL
;
SELECT NOME || ' ' || SOBRENOME AS "Nome completo", COD_DEP
FROM EMPREGADO
WHERE COD_DEP = 100
;
SELECT NOME,ROUND(SALARIO/30,2), ROUND(SALARIO/30)
FROM EMPREGADO
WHERE COD_DEP = 30
ORDER BY NOME
;
SELECT HEM.COD_EMP, HEM.COD_SERVICO, HEM.DATA_FIM - HEM.DATA_INICIO DIAS
FROM HISTORIA_EMPREGADO HEM
WHERE HEM.COD_DEP IN (110 ,50)
;
SELECT COD_DEP, COUNT(1)
FROM EMPREGADO
--WHERE COD_DEP IS NOT NULL
GROUP BY COD_DEP
ORDER BY COD_DEP
;
SELECT COD_SERVICO, SUM(SALARIO) AS TOTAL
FROM EMPREGADO
GROUP BY COD_SERVICO
HAVING SUM(SALARIO) > 15000
ORDER BY SUM(SALARIO)
;
INSERT INTO DEPARTAMENTO (COD_DEP, NOME_DEP, COD_GERENTE, COD_LOCAL)
VALUES (5500, 'UDS', 100, 1700)
;
COMMIT
;
INSERT INTO DEPARTAMENTO (COD_DEP, NOME_DEP, COD_GERENTE, COD_LOCAL)
SELECT COD_EMP + 2000, NOME, COD_GERENTE, NULL
FROM EMPREGADO
WHERE COD_DEP IS NOT NULL
;
COMMIT
;
DELETE
FROM DEPARTAMENTO
WHERE COD_DEP > 2000
;
COMMIT
;
DELETE
FROM DEPARTAMENTO
WHERE COD_DEP NOT IN (
  SELECT DISTINCT COD_DEP
  FROM EMPREGADO
)
;
ROLLBACK
;
SELECT COD_EMP, COD_DEP, COD_SERVICO, NOME, SOBRENOME, SALARIO
--SELECT *
FROM EMPREGADO
WHERE COD_SERVICO = 'ST_CLERK'
;
SELECT COD_EMP, COD_DEP, NOME, SOBRENOME, SALARIO
--SELECT *
FROM EMPREGADO
WHERE COD_EMP IN (127,128,132,135,136)
;
UPDATE EMPREGADO
SET SALARIO = SALARIO * 1.30, COD_DEP = 80
WHERE SALARIO < 2500
;
UPDATE EMPREGADO
SET COD_SERVICO = 'TI'
WHERE COD_SERVICO = 'ST_CLERK'
;
SELECT EMP.COD_EMP, 
       EMP.NOME,
       EMP.COD_DEP, 
       DEP.COD_DEP
FROM EMPREGADO EMP
LEFT JOIN DEPARTAMENTO DEP ON (EMP.COD_DEP = DEP.COD_DEP)
;
SELECT EMP.COD_EMP, 
       EMP.NOME, 
       GER.NOME AS NOME_GERENTE,
       EMP.COD_DEP, 
       DEP.COD_DEP, 
       DEP.NOME_DEP, 
       LOC.CIDADE, 
       PAI.NOME_PAIS, 
       REG.NOME_REGIAO,
       SER.NOME_SERVICO,
       SER.SALARIO_MIN,
       SER.SALARIO_MAX
FROM EMPREGADO EMP
LEFT JOIN DEPARTAMENTO DEP ON (EMP.COD_DEP = DEP.COD_DEP)
LEFT JOIN LOCAL LOC ON (LOC.COD_LOCAL = DEP.COD_LOCAL)
LEFT JOIN PAIS PAI ON (PAI.COD_PAIS = LOC.COD_PAIS)
LEFT JOIN REGIAO REG ON (REG.COD_REGIAO = PAI.COD_REGIAO)
JOIN SERVICO SER ON (EMP.COD_SERVICO = SER.COD_SERVICO)
LEFT JOIN EMPREGADO GER ON (GER.COD_EMP = EMP.COD_GERENTE)
;
SELECT HIS.COD_EMP, 
       EMP.NOME,
       HIS.DATA_INICIO, 
       HIS.DATA_FIM,
       HIS.COD_SERVICO,
       SER.NOME_SERVICO,
       HIS.COD_DEP
FROM HISTORIA_EMPREGADO HIS
JOIN EMPREGADO EMP ON (EMP.COD_EMP = HIS.COD_EMP)
JOIN SERVICO SER ON (SER.COD_SERVICO = HIS.COD_SERVICO)
;

SELECT HIS.COD_EMP, 
       EMP.NOME,
       COUNT(1) AS QTD       
FROM HISTORIA_EMPREGADO HIS
JOIN EMPREGADO EMP ON (EMP.COD_EMP = HIS.COD_EMP)
GROUP BY HIS.COD_EMP, EMP.NOME
ORDER BY EMP.NOME
;
SELECT PAI.NOME_PAIS, REG.NOME_REGIAO
FROM PAIS PAI 
JOIN REGIAO REG ON (REG.COD_REGIAO = PAI.COD_REGIAO)
WHERE REG.NOME_REGIAO = 'Europe'
;
SELECT EMP.NOME, DEP.NOME_DEP, LOC.CIDADE
FROM EMPREGADO EMP
JOIN DEPARTAMENTO DEP ON (EMP.COD_DEP = DEP.COD_DEP)
JOIN LOCAL LOC ON (LOC.COD_LOCAL = DEP.COD_LOCAL)
WHERE LOC.CIDADE = 'Oxford'
;
SELECT EMP.COD_EMP, EMP.NOME, EMP.SALARIO, GER.NOME AS NOME_GERENTE
FROM EMPREGADO EMP
JOIN EMPREGADO GER ON (GER.COD_EMP = EMP.COD_GERENTE)
WHERE EMP.SALARIO > 8000
;
SELECT COUNT(1)
FROM EMPREGADO EMP
JOIN EMPREGADO GER ON (GER.COD_EMP = EMP.COD_GERENTE)
WHERE GER.NOME = 'Steven'
;
SELECT EMP.NOME, EMP.SOBRENOME
FROM EMPREGADO EMP
JOIN SERVICO SER ON (SER.COD_SERVICO = EMP.COD_SERVICO)
WHERE SER.NOME_SERVICO = 'Sales Manager'
UNION ALL
SELECT EMP.NOME, EMP.SOBRENOME
FROM HISTORIA_EMPREGADO HIS
JOIN SERVICO SER ON (SER.COD_SERVICO = HIS.COD_SERVICO)
JOIN EMPREGADO EMP ON (HIS.COD_EMP = EMP.COD_EMP)
WHERE SER.NOME_SERVICO = 'Sales Manager'
;
SELECT DEP.NOME_DEP, LOC.CIDADE, PAI.NOME_PAIS
FROM DEPARTAMENTO DEP
JOIN LOCAL LOC ON (LOC.COD_LOCAL = DEP.COD_LOCAL)
JOIN PAIS PAI ON (PAI.COD_PAIS = LOC.COD_PAIS)
WHERE PAI.NOME_PAIS = 'Germany'
UNION
SELECT DEP.NOME_DEP, LOC.CIDADE, PAI.NOME_PAIS
FROM DEPARTAMENTO DEP
JOIN LOCAL LOC ON (LOC.COD_LOCAL = DEP.COD_LOCAL)
JOIN PAIS PAI ON (PAI.COD_PAIS = LOC.COD_PAIS)
WHERE PAI.NOME_PAIS = 'Canada'
;
INSERT INTO DEPARTAMENTO (COD_DEP, NOME_DEP, COD_GERENTE, COD_LOCAL)
SELECT LEVEL + 280 AS SEQUENCIA, DBMS_RANDOM.STRING('x',10), NULL, NULL
FROM DUAL
CONNECT BY LEVEL <= 1000
;
SELECT LEVEL AS SEQUENCIA, SYSDATE + TRUNC(DBMS_RANDOM.VALUE(1, 1000)) AS DATA_REF
FROM DUAL
CONNECT BY LEVEL <= 1000
;
